I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/puzzles.rpy", line 90, in script
    python:
  File "game/puzzles.rpy", line 92, in <module>
    img_width, img_height = renpy.image_size(chosen_img)
NameError: name 'chosen_img' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/puzzles.rpy", line 90, in script
    python:
  File "/home/fajarikasaputra/renpy-8.0.3-sdk/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/fajarikasaputra/renpy-8.0.3-sdk/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/puzzles.rpy", line 92, in <module>
    img_width, img_height = renpy.image_size(chosen_img)
NameError: name 'chosen_img' is not defined

Linux-5.15.0-52-generic-x86_64-with-glibc2.31 x86_64
Ren'Py 8.0.3.22090809
Majapahit 1.0
Sun Oct 23 17:07:40 2022
